In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cpu
False


In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sentences = [
    "I am good.",
    "I am not bad."
]

# Convert sentences to bag-of-words vectors
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sentences)

# Show vocabulary
print("Vocabulary:", vectorizer.get_feature_names_out())

# Show vectors
print("\nSentence vectors:")
print(X.toarray())

# Cosine similarity
sim = cosine_similarity(X[0], X[1])[0][0]
print("\nCosine similarity (CountVectorizer):", sim)

Vocabulary: ['am' 'bad' 'good' 'not']

Sentence vectors:
[[1 0 1 0]
 [1 1 0 1]]

Cosine similarity (CountVectorizer): 0.408248290463863


In [2]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

sentences = [
    "I am good.",
    "I am not bad."
]

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Create embeddings
embeddings = model.encode(sentences)

# Cosine similarity
sim = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]
print("Cosine similarity (Sentence Embeddings):", sim)

d:\Full-Stack-GenAI-Bootcamp-1.0\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
d:\Full-Stack-GenAI-Bootcamp-1.0\env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\DELL PRECICION\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrato

Cosine similarity (Sentence Embeddings): 0.65466744


In [5]:
from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
embeddings = model.encode(sentences)
print(embeddings)

[[ 6.76569045e-02  6.34959415e-02  4.87130694e-02  7.93049410e-02
   3.74480300e-02  2.65279389e-03  3.93749736e-02 -7.09845126e-03
   5.93614578e-02  3.15370075e-02  6.00980893e-02 -5.29051982e-02
   4.06068079e-02 -2.59308275e-02  2.98428014e-02  1.12690229e-03
   7.35149086e-02 -5.03818654e-02 -1.22386590e-01  2.37028617e-02
   2.97265667e-02  4.24768180e-02  2.56337505e-02  1.99516583e-03
  -5.69190606e-02 -2.71598510e-02 -3.29035223e-02  6.60248846e-02
   1.19007163e-01 -4.58791703e-02 -7.26214275e-02 -3.25840227e-02
   5.23413271e-02  4.50552963e-02  8.25299788e-03  3.67023982e-02
  -1.39415748e-02  6.53918609e-02 -2.64272112e-02  2.06383236e-04
  -1.36643667e-02 -3.62810865e-02 -1.95044372e-02 -2.89738085e-02
   3.94270569e-02 -8.84090737e-02  2.62426562e-03  1.36713833e-02
   4.83062342e-02 -3.11566107e-02 -1.17329173e-01 -5.11690341e-02
  -8.85287970e-02 -2.18963120e-02  1.42986383e-02  4.44167443e-02
  -1.34815695e-02  7.43392035e-02  2.66382992e-02 -1.98762938e-02
   1.79191

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

sentences = [
    "I am good.",
    "I am not bad."
]

# -----------------------------
# Method 1: CountVectorizer
# -----------------------------
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sentences)

print("=== CountVectorizer ===")
print("Vocabulary:", vectorizer.get_feature_names_out())
print("Vectors:")
print(X.toarray())

count_sim = cosine_similarity(X[0], X[1])[0][0]
print("Cosine similarity:", count_sim)

# -----------------------------
# Method 2: Sentence Embeddings
# -----------------------------
model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(sentences)

embed_sim = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]

print("\n=== Sentence Embeddings ===")
print("Embedding shape:", embeddings.shape)
print("Cosine similarity:", embed_sim)

=== CountVectorizer ===
Vocabulary: ['am' 'bad' 'good' 'not']
Vectors:
[[1 0 1 0]
 [1 1 0 1]]
Cosine similarity: 0.408248290463863

=== Sentence Embeddings ===
Embedding shape: (2, 384)
Cosine similarity: 0.65466744


In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sentences = [
    "I am good.",
    "I am not bad."
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("TF-IDF matrix:")
print(X.toarray())

sim = cosine_similarity(X[0], X[1])[0][0]
print("Cosine similarity:", sim)

Vocabulary: ['am' 'bad' 'good' 'not']
TF-IDF matrix:
[[0.57973867 0.         0.81480247 0.        ]
 [0.44943642 0.6316672  0.         0.6316672 ]]
Cosine similarity: 0.26055567105626243
